#!/bin/bash
export NODE_ENV=production

# Set to log detailed debug messages
export DEBUG=mpd.fm:*

# Details of MPD server (Default: localhost:6600)
export MPD_HOST=192.168.1.151
export MPD_PORT=6600

# Port to serve HTTP (the user needs special permission to serve on 80; default: 4200)
export PORT=4200

# JSON file with radio stations. If empty [app root]/data/stations.json will be used
export STATION_FILE=${STATION_FILE:-}

node bin/www
